// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: argus.proto

package argusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Argus_Ping_FullMethodName = "/argus.v1.Argus/Ping"
)

// ArgusClient is the client API for Argus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Argus is the control-plane API of argusd. In M0 it only answers Ping.
type ArgusClient interface {
	// Note: fully qualified, because inside the service block the bare name
	// "Ping" resolves to the method itself, not the message.
	Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type argusClient struct {
	cc grpc.ClientConnInterface
}

func NewArgusClient(cc grpc.ClientConnInterface) ArgusClient {
	return &argusClient{cc}
}

func (c *argusClient) Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, Argus_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArgusServer is the server API for Argus service.
// All implementations must embed UnimplementedArgusServer
// for forward compatibility.
//
// Argus is the control-plane API of argusd. In M0 it only answers Ping.
type ArgusServer interface {
	// Note: fully qualified, because inside the service block the bare name
	// "Ping" resolves to the method itself, not the message.
	Ping(context.Context, *Ping) (*Pong, error)
	mustEmbedUnimplementedArgusServer()
}

// UnimplementedArgusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArgusServer struct{}

func (UnimplementedArgusServer) Ping(context.Context, *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedArgusServer) mustEmbedUnimplementedArgusServer() {}
func (UnimplementedArgusServer) testEmbeddedByValue()               {}

// UnsafeArgusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArgusServer will
// result in compilation errors.
type UnsafeArgusServer interface {
	mustEmbedUnimplementedArgusServer()
}

func RegisterArgusServer(s grpc.ServiceRegistrar, srv ArgusServer) {
	// If the following call pancis, it indicates UnimplementedArgusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Argus_ServiceDesc, srv)
}

func _Argus_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArgusServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Argus_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArgusServer).Ping(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

// Argus_ServiceDesc is the grpc.ServiceDesc for Argus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Argus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.v1.Argus",
	HandlerType: (*ArgusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Argus_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "argus.proto",
}
