// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: argus.proto

package argusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_argus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_argus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_argus_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_argus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_argus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_argus_proto_rawDescGZIP(), []int{1}
}

var File_argus_proto protoreflect.FileDescriptor

const file_argus_proto_rawDesc = "" +
	"\n" +
	"\vargus.proto\x12\bargus.v1\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong2/\n" +
	"\x05Argus\x12&\n" +
	"\x04Ping\x12\x0e.argus.v1.Ping\x1a\x0e.argus.v1.PongB*Z(github.com/jakobneri/argus/proto/argusv1b\x06proto3"

var (
	file_argus_proto_rawDescOnce sync.Once
	file_argus_proto_rawDescData []byte
)

func file_argus_proto_rawDescGZIP() []byte {
	file_argus_proto_rawDescOnce.Do(func() {
		file_argus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_proto_rawDesc), len(file_argus_proto_rawDesc)))
	})
	return file_argus_proto_rawDescData
}

var file_argus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_argus_proto_goTypes = []any{
	(*Ping)(nil), // 0: argus.v1.Ping
	(*Pong)(nil), // 1: argus.v1.Pong
}
var file_argus_proto_depIdxs = []int32{
	0, // 0: argus.v1.Argus.Ping:input_type -> argus.v1.Ping
	1, // 1: argus.v1.Argus.Ping:output_type -> argus.v1.Pong
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_argus_proto_init() }
func file_argus_proto_init() {
	if File_argus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_proto_rawDesc), len(file_argus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_argus_proto_goTypes,
		DependencyIndexes: file_argus_proto_depIdxs,
		MessageInfos:      file_argus_proto_msgTypes,
	}.Build()
	File_argus_proto = out.File
	file_argus_proto_goTypes = nil
	file_argus_proto_depIdxs = nil
}
