// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: argus.proto

package argusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Argus_Ping_FullMethodName          = "/argus.v1.Argus/Ping"
	Argus_GetInventory_FullMethodName  = "/argus.v1.Argus/GetInventory"
	Argus_Attach_FullMethodName        = "/argus.v1.Argus/Attach"
	Argus_StreamMetrics_FullMethodName = "/argus.v1.Argus/StreamMetrics"
	Argus_StreamLogs_FullMethodName    = "/argus.v1.Argus/StreamLogs"
)

// ArgusClient is the client API for Argus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Argus is the control-plane API of argusd.
type ArgusClient interface {
	// Ping answers a liveness probe.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// GetInventory returns a read-only snapshot of systemd services and Docker
	// containers. This RPC is the external API surface (e.g. for MCP consumers);
	// the in-daemon TUI calls the module interfaces directly in-process.
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	// Attach runs one ephemeral headless TUI session inside the daemon.
	// Client -> daemon: raw stdin bytes and terminal resize events.
	// Daemon -> client: rendered terminal frames (ANSI bytes).
	// The session ends when the TUI program exits or the stream closes.
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachRequest, AttachResponse], error)
	// StreamMetrics streams a host + per-container metrics snapshot on a fixed
	// interval until the client disconnects. The streamed message wraps a
	// MetricsSnapshot (the buf STANDARD naming rules require the response type to
	// be named after the RPC; see proto naming note below).
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMetricsResponse], error)
	// StreamLogs streams unified log entries from the systemd journal and/or
	// Docker until the client disconnects. The streamed message wraps a LogEntry.
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamLogsResponse], error)
}

type argusClient struct {
	cc grpc.ClientConnInterface
}

func NewArgusClient(cc grpc.ClientConnInterface) ArgusClient {
	return &argusClient{cc}
}

func (c *argusClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Argus_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *argusClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, Argus_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *argusClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachRequest, AttachResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Argus_ServiceDesc.Streams[0], Argus_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachRequest, AttachResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Argus_AttachClient = grpc.BidiStreamingClient[AttachRequest, AttachResponse]

func (c *argusClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Argus_ServiceDesc.Streams[1], Argus_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, StreamMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Argus_StreamMetricsClient = grpc.ServerStreamingClient[StreamMetricsResponse]

func (c *argusClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Argus_ServiceDesc.Streams[2], Argus_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, StreamLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Argus_StreamLogsClient = grpc.ServerStreamingClient[StreamLogsResponse]

// ArgusServer is the server API for Argus service.
// All implementations must embed UnimplementedArgusServer
// for forward compatibility.
//
// Argus is the control-plane API of argusd.
type ArgusServer interface {
	// Ping answers a liveness probe.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// GetInventory returns a read-only snapshot of systemd services and Docker
	// containers. This RPC is the external API surface (e.g. for MCP consumers);
	// the in-daemon TUI calls the module interfaces directly in-process.
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	// Attach runs one ephemeral headless TUI session inside the daemon.
	// Client -> daemon: raw stdin bytes and terminal resize events.
	// Daemon -> client: rendered terminal frames (ANSI bytes).
	// The session ends when the TUI program exits or the stream closes.
	Attach(grpc.BidiStreamingServer[AttachRequest, AttachResponse]) error
	// StreamMetrics streams a host + per-container metrics snapshot on a fixed
	// interval until the client disconnects. The streamed message wraps a
	// MetricsSnapshot (the buf STANDARD naming rules require the response type to
	// be named after the RPC; see proto naming note below).
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[StreamMetricsResponse]) error
	// StreamLogs streams unified log entries from the systemd journal and/or
	// Docker until the client disconnects. The streamed message wraps a LogEntry.
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[StreamLogsResponse]) error
	mustEmbedUnimplementedArgusServer()
}

// UnimplementedArgusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArgusServer struct{}

func (UnimplementedArgusServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedArgusServer) GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedArgusServer) Attach(grpc.BidiStreamingServer[AttachRequest, AttachResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedArgusServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[StreamMetricsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedArgusServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[StreamLogsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedArgusServer) mustEmbedUnimplementedArgusServer() {}
func (UnimplementedArgusServer) testEmbeddedByValue()               {}

// UnsafeArgusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArgusServer will
// result in compilation errors.
type UnsafeArgusServer interface {
	mustEmbedUnimplementedArgusServer()
}

func RegisterArgusServer(s grpc.ServiceRegistrar, srv ArgusServer) {
	// If the following call pancis, it indicates UnimplementedArgusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Argus_ServiceDesc, srv)
}

func _Argus_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArgusServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Argus_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArgusServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Argus_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArgusServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Argus_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArgusServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Argus_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArgusServer).Attach(&grpc.GenericServerStream[AttachRequest, AttachResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Argus_AttachServer = grpc.BidiStreamingServer[AttachRequest, AttachResponse]

func _Argus_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ArgusServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, StreamMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Argus_StreamMetricsServer = grpc.ServerStreamingServer[StreamMetricsResponse]

func _Argus_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ArgusServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, StreamLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Argus_StreamLogsServer = grpc.ServerStreamingServer[StreamLogsResponse]

// Argus_ServiceDesc is the grpc.ServiceDesc for Argus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Argus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.v1.Argus",
	HandlerType: (*ArgusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Argus_Ping_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _Argus_GetInventory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _Argus_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamMetrics",
			Handler:       _Argus_StreamMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _Argus_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "argus.proto",
}
